name: push-alert-to-slack-channel

on:
  pull_request:
    paths:
      - .github/workflows/alert-noti.yaml
      - infra/**
      - package.json
      - lib/**

permissions:
  id-token: write
  contents: read

env:
  ENV: dev
  REGION: ap-southeast-1

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      stageName: ${{ steps.env-setting.outputs.stageName }}
      awsRoleArn: ${{ steps.env-setting.outputs.awsRoleArn }}
    steps:
      - id: env-setting
        run: |
          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
          if [[ $TARGET_BRANCH == "main" ]]; then
            echo "Setting environment to dev"
            echo "stageName=dev" >> $GITHUB_OUTPUT
            echo "awsRoleArn=arn:aws:iam::967779793699:role/DeployRole" >> $GITHUB_OUTPUT         
          else
            echo "No specific condition met. No environment variable set (set to dev)"
            echo "stageName=dev" >> $GITHUB_OUTPUT
            echo "awsRoleArn=arn:aws:iam::967779793699:role/DeployRole" >> $GITHUB_OUTPUT
          fi
  run-aws:
    runs-on: ubuntu-latest
    needs: set-env
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
              node-version-file: "package.json"
              cache: npm

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
              role-to-assume: ${{ needs.set-env.outputs.awsRoleArn }}
              aws-region: ${{ env.REGION }}

        - name: Fetch AWS SSM parameters
          uses: dkershner6/aws-ssm-getparameters-action@v2
          with:
              parameterPairs: "SLACK_WEBHOOK_URL = SLACK_WEBHOOK_URL"
    

        - name: check assume role
          run: aws sts get-caller-identity
    
        - name: Install dependencies if cache does not exist
          run: npm ci

        - name: Cdk diff resource
          run: npm run cdk diff infraStack

        - name: pushalert to slack channel
          if: ${{ success() || failure() }}
          uses: 8398a7/action-slack@v3
          with:
            status: ${{ job.status }}
            fields: pullRequest,author,workflow
            custom_payload: |
              {
                attachments: [{
                  color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger',
                  text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
                }]
              }
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            if: always()