name: ci-infra-check

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  REGION: ap-southeast-1
  ENVIRONMENT: dev

jobs:
  ci-infra:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setting up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          custom_payload: |
            ({
              username: "${{ github.event.repository.name }}",
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : 'danger',
                text: `Workflow: ${{ github.workflow }}\nRepo: ${{ github.event.repository.name }}`
              }]
            })
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
