name: deploy infra Stack

on:
  push:
    tags:
      - 'stg-v[0-9]+.[0-9]+.[0-9]+'
    paths:
      - "bin/**"
      - "lib/**"
      - ".github/workflows/deploy-infra-stg.yaml"

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  infra-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: npm
      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_DEPLOY }}
          aws-region: ap-southeast-1

      - name: Verify AWS credentials
        run: aws sts get-caller-identity
      
      - name: CDK Deploy
        run: npm run cdk deploy GithubActionsOidcStack




        


