name: deploy infra Stack

on:
  push:
    branches:
      - main
    paths:
      - "bin/**"
      - "lib/**"
      - ".github/workflows/deploy-infra-dev.yaml"

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  infra-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/setup-node@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version-file: "package.json"
            cache: npm

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ASSUME_ROLE }}
          aws-region: ap-southeast-1

      - name: Verify AWS credentials
        run: aws sts get-caller-identity

      - name: Install dependencies
        run: npm ci

      - name: Deploy GithubActionsOidcStack
        run: npm run cdk deploy GithubActionsOidcStack

      - name: Deploy infraStack
        run: npm run cdk deploy GithubActionsOidcStack
