name: deploy infra Stack

on:
  push:
    branches:
      - main
    paths:
      - "bin/**"
      - "lib/**"
      - ".github/workflows/deploy-infra-dev.yaml"

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  infra-deploy:
    environment: dev
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/setup-node@v4

      - name: Setting up Node 16
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEV_IAM_ROLE_DEPLOY}}
          role-duration-seconds: 3600
          aws-region: ap-southeast-1

      - name: Install Node dependencies
        run: npm ci

      - name: Verify AWS credentials
        run: aws sts get-caller-identity

      - name: Deploy GithubActionsOidcStack
        run: npm run cdk deploy GithubActionsOidcStack

      - name: Deploy infraStack
        run: npm run cdk deploy GithubActionsOidcStack
