on: 
    push:
      branches:
         'main'
permissions:
  id-token: write
  contents: read
jobs:
    new_push_job:
      runs-on: ubuntu-latest
      name: New push to repo
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::967779793699:role/DeployRole
            aws-region: ap-southeast-1

        - name: Fetch AWS SSM parameters
          uses: dkershner6/aws-ssm-getparameters-action@v1
          with:
            parameterPairs: 
             "SLACK_WEBHOOK_URL = SLACK_WEBHOOK_URL"
        - name: pushalert to slack channel
          uses: 8398a7/action-slack@v3
          with:
            status: ${{ job.status }}
            fields: repo,message,commit,author,action,workflow,job,pullRequest
            custom_payload: |
              {
                attachments: [{
                  color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                  text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
                }]
              }
          env:
            SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
            if: always()
