on: 
    push:
      branches:
         'main'

 
jobs:
    new_push_job:
      runs-on: ubuntu-latest
      name: New push to repo
      steps:
        - name: Succeeded Check
          uses: 8398a7/action-slack@v3
          with:
           status: success
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        