on: 
    push:
      branches:
         '*'
  
jobs:
    new_push_job:
      runs-on: ubuntu-latest
      name: New push to repo
      steps:
        - name: Send GitHub trigger payload to Slack Workflow Builder
          uses: slackapi/slack-github-action@v1.25.0
          with:
            payload: |
              {
                "text": "hello"
              }       
          env:
            SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK