on: 
    push:
      branches:
         'main'
jobs:
    new_push_job:
      runs-on: ubuntu-latest
      name: New push to repo
      steps:
        # - name: Failed Check
        #   uses: 8398a7/action-slack@v3
        #   with:
        #    status: failure
        #   env:
        #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        # - name: Cancelled Check
        #   uses: 8398a7/action-slack@v3
        #   with:
        #     status: cancelled
        #   env:
        #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        # - name: Check
        #   uses: 8398a7/action-slack@v3
        #   with:
        #       status: ${{ job.status }}
        #   env:
        #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        # - name: Legacy Check
        #   uses: 8398a7/action-slack@v3
        #   with:
        #       status: ${{ job.status }}
        #       username: legacy user
        #       icon_emoji: ":octocat:"
        #   env:
        #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
        - name: Fields Check
          uses: 8398a7/action-slack@v3
          with:
                status: ${{ job.status }}
                fields: repo,message,commit,author,job,eventName,ref,workflow,took
          env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        - uses: 8398a7/action-slack@v3
          with:
                status: ${{ job.status }}
                fields: repo,message,job,took
          env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    matrix-notification:
          strategy:
            matrix:
              os: [ubuntu-20.04, ubuntu-22.04]
          runs-on: ${{ matrix.os }}
          # steps:
          #   - uses: 8398a7/action-slack@v3
          #     with:
          #       status: ${{ job.status }}
          #       fields: job,took
          #     env:
          #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FOR_INTEGRATION_TEST }}
          #       MATRIX_CONTEXT: ${{ toJson(matrix) }}
          #     if: always()